{
    "0.1.0": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.0/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "729cea806e402fc7d40f2b57a9055504",
                    "sha256": "39d1d131913ca39385c09de98f116d967d300384afbcb845f915bc04b7f5c105"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.0-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "729cea806e402fc7d40f2b57a9055504",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 4918,
                "upload_time": "2022-05-20T08:07:53",
                "upload_time_iso_8601": "2022-05-20T08:07:53.089991Z",
                "url": "https://files.pythonhosted.org/packages/db/1e/617fc4742e2166f78ad37937c19add79103f33a017ce131621b0a9385fab/teleexception-0.1.0-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.1": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.1/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.1",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "40fd35f83d5322d54b3452191992f342",
                    "sha256": "d2e8563434315aefa1f8890696e52c59e6d7048cf90eb020ca23c6b57a3ed189"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.1-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "40fd35f83d5322d54b3452191992f342",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5858,
                "upload_time": "2022-06-13T10:19:46",
                "upload_time_iso_8601": "2022-06-13T10:19:46.012739Z",
                "url": "https://files.pythonhosted.org/packages/c7/2d/81344b51bb947620c812b84a5383098d9ea92f67c6b0c3cc89a2ccb01c7f/teleexception-0.1.1-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.10": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.10/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.10",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "8eb01630f74f11c64d4d607091cf0b5f",
                    "sha256": "d31c7bd2b7fd450ff17f3bc7d3a893b0957fdd61554d6998bb4d61cfb6dfaca7"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.10-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "8eb01630f74f11c64d4d607091cf0b5f",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5796,
                "upload_time": "2022-08-16T03:04:07",
                "upload_time_iso_8601": "2022-08-16T03:04:07.359318Z",
                "url": "https://files.pythonhosted.org/packages/82/3b/fd8372b6148c9000ec186ae2ebd9ca911cdafa691f75cca4ae172c82901b/teleexception-0.1.10-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.11": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.11/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.11",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "20ca691eaf1381e49b83a161f9840d6b",
                    "sha256": "30ea064789712828f9267a98541cd7a09a7bafcf5d2ac600a6f4e601de493cff"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.11-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "20ca691eaf1381e49b83a161f9840d6b",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5912,
                "upload_time": "2022-08-25T00:57:57",
                "upload_time_iso_8601": "2022-08-25T00:57:57.345113Z",
                "url": "https://files.pythonhosted.org/packages/68/9c/9716d8dfbdfe76c4955e14a672012100f32beb227176d7a5a1d22c19e9ba/teleexception-0.1.11-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.12": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.12/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.12",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "53d35b1665226f77b031aaa05a13ffad",
                    "sha256": "9c40b571f46f6aea79ae2cb3bcc3b23366187327411e17f24f19853a09eba629"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.12-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "53d35b1665226f77b031aaa05a13ffad",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5975,
                "upload_time": "2022-08-31T01:03:10",
                "upload_time_iso_8601": "2022-08-31T01:03:10.660044Z",
                "url": "https://files.pythonhosted.org/packages/1e/20/409816d7d3a39995974708b3564fd27e315a210e73bc99bc2facb2ee50c3/teleexception-0.1.12-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.13": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.13/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.13",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "4394797e35dbace07ec1c563cbc99b0d",
                    "sha256": "14c1ab4be791aa5b99377dbdd4dca5d3b910d77b0400137ec17fb407f4732381"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.13-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "4394797e35dbace07ec1c563cbc99b0d",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6039,
                "upload_time": "2022-09-02T08:28:16",
                "upload_time_iso_8601": "2022-09-02T08:28:16.106340Z",
                "url": "https://files.pythonhosted.org/packages/54/80/e9b66372a5edc545ef9a345fde0d5e9e12fe70234c1eeb6a5810e2a4efad/teleexception-0.1.13-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.14": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.14/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.14",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "ef4261365825850413200bcf9338cb4d",
                    "sha256": "3d7554f9e7c81fe360268333e72127711a1c8c018a29b4083bcd280241e070f6"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.14-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "ef4261365825850413200bcf9338cb4d",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6183,
                "upload_time": "2022-09-07T06:28:18",
                "upload_time_iso_8601": "2022-09-07T06:28:18.337034Z",
                "url": "https://files.pythonhosted.org/packages/2f/ca/8f709c1050b7da32c4c5584e6a1425d7bf834e2859480a33ecd52bc9d854/teleexception-0.1.14-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.15": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.15/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.15",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "2d31af5a7484ae662fffeadab938362f",
                    "sha256": "cc9766dfcdc09e3da53b23c11852ce4b37b59196f544484e0801224f5675920f"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.15-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "2d31af5a7484ae662fffeadab938362f",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6231,
                "upload_time": "2022-09-09T02:24:29",
                "upload_time_iso_8601": "2022-09-09T02:24:29.626480Z",
                "url": "https://files.pythonhosted.org/packages/d1/b6/478abd1db887aab9faa37fc0c233040dc921d3fc4b992ac02121ab657c32/teleexception-0.1.15-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.16": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.16/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.16",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "48f3907ff90a34ca38f25b66f39f5af1",
                    "sha256": "9d0ea6174746846971ab6f8fa16463324e78eec4838b97c189a89e035a16d433"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.16-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "48f3907ff90a34ca38f25b66f39f5af1",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6324,
                "upload_time": "2022-09-13T01:40:26",
                "upload_time_iso_8601": "2022-09-13T01:40:26.172641Z",
                "url": "https://files.pythonhosted.org/packages/bf/12/7d29d458b2793478614a750a492341d7f6a1d535866d8938b7464b56899d/teleexception-0.1.16-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.17": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.17/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.17",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "af8ee52b3c84161d0422eef32bef855e",
                    "sha256": "c8496cf304ae9f42e2683fe356ef0261a393c41f49912039f1549ce8f70b96c9"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.17-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "af8ee52b3c84161d0422eef32bef855e",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6922,
                "upload_time": "2022-10-08T03:17:25",
                "upload_time_iso_8601": "2022-10-08T03:17:25.096894Z",
                "url": "https://files.pythonhosted.org/packages/19/04/a874c3bae0cb074db7460ad8660bc19c105a7c7e19887b1d06bc50a52d11/teleexception-0.1.17-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.18": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.18/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.18",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "6be2c58ed19c645662b2da55476d136b",
                    "sha256": "bd571397b2e5e906ec4ff180a0f114cb91d859f37aaea2665ac8d9bea08393d7"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.18-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "6be2c58ed19c645662b2da55476d136b",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 7439,
                "upload_time": "2022-10-11T01:26:16",
                "upload_time_iso_8601": "2022-10-11T01:26:16.519327Z",
                "url": "https://files.pythonhosted.org/packages/ac/f9/36e942427339ef02148292b0f25f8d4d6e70a1efd41f425b461b2dd453e8/teleexception-0.1.18-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.19": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.19/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.19",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "0c88cac8f8140e8b35930f465300d034",
                    "sha256": "0cb6a7368936a34598b96987219de9f97556ee28ef28f842f1e10a09faa19f13"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.19-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "0c88cac8f8140e8b35930f465300d034",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 7486,
                "upload_time": "2022-10-14T07:28:31",
                "upload_time_iso_8601": "2022-10-14T07:28:31.153079Z",
                "url": "https://files.pythonhosted.org/packages/e9/30/c6e90db22ab7df3968dfc28eb512973085147ea8023230e2525999cbd236/teleexception-0.1.19-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.2": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.2/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.2",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "5f0598a72c9fa10ba7592bdcc41e6e94",
                    "sha256": "af3c29423b95d8c43a96a5f011e0e0eb3dea9faa6f6bb1a2e02d8853ed6607d7"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.2-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "5f0598a72c9fa10ba7592bdcc41e6e94",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5858,
                "upload_time": "2022-06-14T03:42:12",
                "upload_time_iso_8601": "2022-06-14T03:42:12.262571Z",
                "url": "https://files.pythonhosted.org/packages/9c/ac/d73f6ab222cd59400bc4b3f8b8080d3909428080e9fc08bbede29971eaef/teleexception-0.1.2-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.20": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.20/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.20",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "4321730516a680a2167dea43b3bd55b4",
                    "sha256": "1e8e38d7c619a2a657572b61e16790fec00385bca0b3f4e83c1ec08f304dbf0d"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.20-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "4321730516a680a2167dea43b3bd55b4",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 7499,
                "upload_time": "2022-10-17T02:11:31",
                "upload_time_iso_8601": "2022-10-17T02:11:31.420869Z",
                "url": "https://files.pythonhosted.org/packages/64/a8/b884e68170633496a8578d9363f9debbd8a8d5f6f69b8d7297ce61023f0b/teleexception-0.1.20-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.21": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.21/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.21",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "db65af01d1a807db9f06091134056435",
                    "sha256": "c99d2d68f97267fc946ae35c8fc26ccdcd80d9ecccf2fe80bbe11842c398c54e"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.21-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "db65af01d1a807db9f06091134056435",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 7502,
                "upload_time": "2022-10-17T06:44:04",
                "upload_time_iso_8601": "2022-10-17T06:44:04.381902Z",
                "url": "https://files.pythonhosted.org/packages/41/4a/2b95f01662df66ec8c22dff117d8c9d4a01ad128639c39fc428e5ec9391e/teleexception-0.1.21-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.3": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.3/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.3",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "c2569042b60708ab10322165c6d7b066",
                    "sha256": "4d90ba3dc276253e2051880e4b6691412ef064c53f13bd47ddb6ef170801ebcd"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.3-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "c2569042b60708ab10322165c6d7b066",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5801,
                "upload_time": "2022-06-15T02:46:12",
                "upload_time_iso_8601": "2022-06-15T02:46:12.189509Z",
                "url": "https://files.pythonhosted.org/packages/3d/1a/7c763c63c9695395dfeadb5d9a0c2ae6d9c9540a3ab350bc1c58f117dd05/teleexception-0.1.3-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.4": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.4/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.4",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "c618e2c241f498cf91864ec37c53db85",
                    "sha256": "51684cf1550861ed7e72c3a8436eb08c253626f0f9d21fe6c9935b103ac51618"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.4-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "c618e2c241f498cf91864ec37c53db85",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6198,
                "upload_time": "2022-07-19T11:16:18",
                "upload_time_iso_8601": "2022-07-19T11:16:18.061146Z",
                "url": "https://files.pythonhosted.org/packages/2b/2f/69f2804873ed414c9c03821bdb973e0107c9324fa04f91955986138bd2ee/teleexception-0.1.4-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.5": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.5/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.5",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "7b6451ed158c6f320d5ceedbc4060427",
                    "sha256": "ddeb601b38f2d4cd7c5638845dc5664fe6ca14b28c268fbcd6415d16ae06301f"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.5-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "7b6451ed158c6f320d5ceedbc4060427",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 6605,
                "upload_time": "2022-07-20T07:44:26",
                "upload_time_iso_8601": "2022-07-20T07:44:26.739112Z",
                "url": "https://files.pythonhosted.org/packages/e9/5a/5574c0fc321ac99056bef6410820835d19b61305016907c7161ead0857cf/teleexception-0.1.5-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.6": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.6/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.6",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "1af0a69d0d656ea51ff09fb8a6c6e516",
                    "sha256": "1c27b0a9d3e7fc95987367fdecf1c67bf0c4a54d338eecd292de5fdace87b155"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.6-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "1af0a69d0d656ea51ff09fb8a6c6e516",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 7116,
                "upload_time": "2022-07-27T07:45:01",
                "upload_time_iso_8601": "2022-07-27T07:45:01.944880Z",
                "url": "https://files.pythonhosted.org/packages/5c/d0/14c08fdcebbe655e5a95516cff3093cead84b59a4066d3391994218eda39/teleexception-0.1.6-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.7": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.7/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.7",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "06e66ace251a2096955d7d518e4ae680",
                    "sha256": "ba2d4aff711088e7de5464a1b7aa28f7a91bb4c600b3a112ba5402057418c264"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.7-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "06e66ace251a2096955d7d518e4ae680",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 7107,
                "upload_time": "2022-07-27T09:14:09",
                "upload_time_iso_8601": "2022-07-27T09:14:09.064193Z",
                "url": "https://files.pythonhosted.org/packages/29/12/29851c31a19bf9ee53ddb7da05b1eab791794f6580a33fa9dbe6fe54d063/teleexception-0.1.7-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.8": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.8/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.8",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "d94d36ae5af1f5b636908818f84572c8",
                    "sha256": "ed75071ea01029febd7e2b36ad697224e25ee72a9c970e27ccecdd60a687647b"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.8-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "d94d36ae5af1f5b636908818f84572c8",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5531,
                "upload_time": "2022-08-05T03:37:26",
                "upload_time_iso_8601": "2022-08-05T03:37:26.217049Z",
                "url": "https://files.pythonhosted.org/packages/52/80/d37002e21bdf156dac50aa61d3b86ad8c528a6dc19ac18863a9b0e486040/teleexception-0.1.8-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.1.9": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.1.9/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.1.9",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "3647d7112a3f4ea8193c597f5500df25",
                    "sha256": "210bfb5f0f9376cbaae5aaffd4116026878db7afc6add5479bbb14fc4d55024b"
                },
                "downloads": -1,
                "filename": "teleexception-0.1.9-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "3647d7112a3f4ea8193c597f5500df25",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 5615,
                "upload_time": "2022-08-08T01:53:54",
                "upload_time_iso_8601": "2022-08-08T01:53:54.874665Z",
                "url": "https://files.pythonhosted.org/packages/1d/20/5149a81e6ad95567ea42f9a8f118d67e0921ea271fa605021c177449a844/teleexception-0.1.9-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.0": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.0/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "6808c9b48f601d98368c27b984e9eebd",
                    "sha256": "8567216b317b2513b391d85d718ce4242ea312e5adb25f1f23ffe2a95db9c900"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.0-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "6808c9b48f601d98368c27b984e9eebd",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 8018,
                "upload_time": "2022-10-19T01:08:07",
                "upload_time_iso_8601": "2022-10-19T01:08:07.654217Z",
                "url": "https://files.pythonhosted.org/packages/03/5a/3d315b83333aed02f36877bd65a8ad8f6ddae2bec52309da97707ded30e5/teleexception-0.2.0-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.1": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.1/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.1",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "141b0332c9cf5a046a27a5b3b8cead2d",
                    "sha256": "3df2191796265e7f3ac1a5ac1144157293e0c08036131912489b0aff4ac5d6c3"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.1-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "141b0332c9cf5a046a27a5b3b8cead2d",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 8078,
                "upload_time": "2022-10-19T06:20:27",
                "upload_time_iso_8601": "2022-10-19T06:20:27.518224Z",
                "url": "https://files.pythonhosted.org/packages/54/4e/2bd22c6141420409df4906e0e07e1c176c36e936aa3230bb90bffb9d1807/teleexception-0.2.1-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.10": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.10/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.10",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "81edc9b4c72eae6d716130801c8a3045",
                    "sha256": "a68da3bd66c666dcee44ce47deb55f8544c003a454a42a3bda8e718093494d80"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.10-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "81edc9b4c72eae6d716130801c8a3045",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9847,
                "upload_time": "2022-11-13T11:46:26",
                "upload_time_iso_8601": "2022-11-13T11:46:26.443815Z",
                "url": "https://files.pythonhosted.org/packages/0e/3d/5c791f7545588ac0b2068bfa76807e5e7acc4e08e0a310b016174d948e80/teleexception-0.2.10-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.11": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.11/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.11",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "8fe272df476037557cef14e712927de6",
                    "sha256": "ca8eb94197eae9a040ae09f0bb933651b826f3c517f2bc162064f95091fa6be3"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.11-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "8fe272df476037557cef14e712927de6",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9876,
                "upload_time": "2022-11-15T00:40:31",
                "upload_time_iso_8601": "2022-11-15T00:40:31.746262Z",
                "url": "https://files.pythonhosted.org/packages/93/47/eb3ace61a78df3798edb8de309f1ad4dfd4a99ec53060763674120a6a782/teleexception-0.2.11-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.12": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.12/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.12",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "a265349222144440d08b7e1361ee786a",
                    "sha256": "e9a79615b3d4fa5838c003fcebac408ed29484c9bd7accc1642182ff3ab04346"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.12-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "a265349222144440d08b7e1361ee786a",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9927,
                "upload_time": "2022-11-21T02:38:53",
                "upload_time_iso_8601": "2022-11-21T02:38:53.817794Z",
                "url": "https://files.pythonhosted.org/packages/f0/7c/2ab0aa5e97f3c0d1c40dff2d203175871c6741ddc5576b1a3cc7774ba2e9/teleexception-0.2.12-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.13": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.13/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.13",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "5da0859a57c28cae38ff48cb741aec67",
                    "sha256": "df1610c5b1ac7002e35b2a96ddde622e786ec62295653cba44b5ce394781cb81"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.13-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "5da0859a57c28cae38ff48cb741aec67",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9943,
                "upload_time": "2022-11-28T06:17:18",
                "upload_time_iso_8601": "2022-11-28T06:17:18.114288Z",
                "url": "https://files.pythonhosted.org/packages/3b/2c/a7f131e4a626ab45b6e86d8779bc1457a9c97c5cd2c1bb31ab6ee1226f46/teleexception-0.2.13-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.14": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.14/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.14",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "0b7bb5bd810e558e371b6ce92436db5f",
                    "sha256": "468bec8c4eda2034c154e9e627d30ef4ebe676dfca5e5ba0c8ad440c08e7838f"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.14-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "0b7bb5bd810e558e371b6ce92436db5f",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9950,
                "upload_time": "2022-12-06T12:59:09",
                "upload_time_iso_8601": "2022-12-06T12:59:09.431673Z",
                "url": "https://files.pythonhosted.org/packages/20/25/ec888b2ef9e092e85c04e069ba8bdfdde7b386be4856a848509496fb87a0/teleexception-0.2.14-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.2": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.2/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.2",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "6ab1c2e8d36b99dc7eec1fddd33c16ac",
                    "sha256": "cef8cdba000f84c4ef61379df89feae7ccc2c976ddb139b7bb1aa3a8e99c05a1"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.2-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "6ab1c2e8d36b99dc7eec1fddd33c16ac",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 8090,
                "upload_time": "2022-10-19T09:08:14",
                "upload_time_iso_8601": "2022-10-19T09:08:14.930099Z",
                "url": "https://files.pythonhosted.org/packages/5d/5c/42020b216d55e7d7afbeb488c6ddc710311ca7803f1b7abad54f2eef69fc/teleexception-0.2.2-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.3": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.3/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.3",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "f126c0f9a787c3ba9f325f5839f0374f",
                    "sha256": "53abec861b9fbab23379b2698ce6950780d190e197addd3640d23af182cd11de"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.3-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "f126c0f9a787c3ba9f325f5839f0374f",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 8124,
                "upload_time": "2022-10-20T02:14:12",
                "upload_time_iso_8601": "2022-10-20T02:14:12.382299Z",
                "url": "https://files.pythonhosted.org/packages/f9/b5/1f918bd9791ddb29b95a1560b612b7d585e7ab4f18b1a4833b046732387b/teleexception-0.2.3-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.4": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.4/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.4",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "d7280617bcc9fcee42a073e0fc1f8247",
                    "sha256": "74b1b4ac54563b288c92de5787b57be00795e9e11f7c28c216be6c5392bd456c"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.4-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "d7280617bcc9fcee42a073e0fc1f8247",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 8123,
                "upload_time": "2022-10-21T01:09:15",
                "upload_time_iso_8601": "2022-10-21T01:09:15.851918Z",
                "url": "https://files.pythonhosted.org/packages/e8/1d/e454452db8335408bea6acd95c7f1e8b71317a8663e4de43ad5e803ea3e1/teleexception-0.2.4-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.5": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.5/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.5",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "82e8221217c8cf22509c56d7c66472b7",
                    "sha256": "0595082020c02e94abb22f9aee97480f931c08e08e3fba13aa6a2f151b908672"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.5-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "82e8221217c8cf22509c56d7c66472b7",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 8535,
                "upload_time": "2022-10-28T03:28:30",
                "upload_time_iso_8601": "2022-10-28T03:28:30.623979Z",
                "url": "https://files.pythonhosted.org/packages/9e/e5/249232d2be69641dc6f944adbf41b44152cf569c6607f3bc1111d3797201/teleexception-0.2.5-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.6": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.6/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.6",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "888f68c7cadfc0a121ae4ea9fdd25cf0",
                    "sha256": "a3fd32d9d73eec008842d4c65003906fc7f2091f7491d5eba5791c7ef7ff0e41"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.6-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "888f68c7cadfc0a121ae4ea9fdd25cf0",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9714,
                "upload_time": "2022-10-28T08:52:37",
                "upload_time_iso_8601": "2022-10-28T08:52:37.656163Z",
                "url": "https://files.pythonhosted.org/packages/41/7e/7e7404469eb91118652d99e48c4d2f35cd39eb5fca6328f88833c576ba61/teleexception-0.2.6-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.7": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.7/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.7",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "e51255b7427f39836a6e85940a00a1ba",
                    "sha256": "2777a171995d3ed83208c1eb678c2f155a4e6b02491a889ea4bf7f55b62681c7"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.7-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "e51255b7427f39836a6e85940a00a1ba",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9721,
                "upload_time": "2022-10-30T03:47:44",
                "upload_time_iso_8601": "2022-10-30T03:47:44.763548Z",
                "url": "https://files.pythonhosted.org/packages/23/12/53eacbdc4ff966726b1e035e673059c9454462ada1b20fd42ed9db20b625/teleexception-0.2.7-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.8": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.8/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.8",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "9fdad32e03789b579ba1445fcb5e88e8",
                    "sha256": "3fe2ebc3e6b0c18c9ea2693661850460a5605eda80fb7b7534c5134a0de63310"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.8-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "9fdad32e03789b579ba1445fcb5e88e8",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9773,
                "upload_time": "2022-11-01T11:55:55",
                "upload_time_iso_8601": "2022-11-01T11:55:55.901538Z",
                "url": "https://files.pythonhosted.org/packages/bd/86/1b78e1492bdc516e1673b7147b5a8ed33c5e36fee983b86054929803b65c/teleexception-0.2.8-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    },
    "0.2.9": {
        "info": {
            "author": "imason",
            "author_email": "635761952@qq.com",
            "bugtrack_url": null,
            "classifiers": [
                "License :: OSI Approved :: MIT License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3"
            ],
            "description": "Tele Log\n==========================\n\n\u7edf\u4e00\u7684\u5f02\u5e38\u7c7b python package\u3002\n\n## how to commpile\n```bash\npython setup.py sdist bdist_wheel\n```\n\n## how to release\n```bash\ntwine upload -r pypi dist/*.whl\n```\n\n## how to install \n```bash\npip install teleexception\n```\n\n## how to use\n```python\nfrom teleexception import HTTPStatus, StatusException\nstatus = HTTPStatus.FORBIDDEN\nraise StatusException(status.value, status.phrase)\n```\n\n\n\n## \u7248\u672c\uff1a\n\n\u9519\u8bef\u7801\u5b9a\u4e49\u89c4\u8303\uff082022.10.18\uff09\uff1ahttps://doc.weixin.qq.com/sheet/e3_AQ4AhgZUAJ83tl2k4qhSeaoRLQ2T0?scode=AGIACAeJAA0NBzCa2KARYAMgazAD0\n\n- 0.1.x\uff1a\u65e7\u7248\u9519\u8bef\u7801\uff08\u6ca1\u6709\u590d\u7528\uff0c\u5df2\u5f03\u7528\uff09\n- **0.2.x\uff1a\u65b0\u7248\u9519\u8bef\u7801\uff08\u590d\u7528\u9519\u8bef\u7801\uff09**\n\n**\u9519\u8bef\u7801\u4f4d\u6570\u5747\u4e3a 6 \u4f4d\u6570\uff0c\u5171\u5206\u4e3a 8 \u5927\u7c7b\uff1a**\n\n- \u901a\u7528\u9519\u8bef\u7801\uff1a4xxxxx\n  - \u901a\u7528\uff1a40xxxx\n  - \u56fe\u7247\uff1a41xxxx\n  - \u6587\u672c\uff1a42xxxx\n  - \u97f3\u9891\uff1a43xxxx\n  - \u89c6\u9891\uff1a44xxxx\n  - \u6570\u636e\u5e93\uff1a45xxxx\n- \u7cfb\u7edf\u8fd0\u884c\u9519\u8bef\u7801\uff1a5xxxxx\n\n- \u4e1a\u52a1\u76f8\u5173\u9519\u8bef\u7801\uff1a6xxxxx\n  - \u4eba\u4f53\u76f8\u5173\u4e1a\u52a1\uff1a600xxx\n  - \u4eba\u8138\u76f8\u5173\u4e1a\u52a1\uff1a601xxx\n\n**\u8bf4\u660e\uff1a\u9519\u8bef\u7801\u548c message \u4e00\u4e00\u5bf9\u5e94\uff0cdetails \u6839\u636e\u4e1a\u52a1\u5b57\u6bb5\u9009\u62e9\u6027\u8fd4\u56de\u63cf\u8ff0\u6027\u8bf4\u660e\uff0c\u4e0d\u505a\u5f3a\u5236\u89c4\u5b9a\u3002**\n\n| \u9519\u8bef\u7801 |           message            | details |\n| :----: | :--------------------------: | :-----: |\n| 400001 |         \u8bf7\u6c42\u8def\u5f84\u9519\u8bef         |         |\n| 400002 |         \u8bf7\u6c42\u65b9\u6cd5\u9519\u8bef         |         |\n| 400003 |        \u8bf7\u6c42\u4f53\u5185\u5bb9\u4e3a\u7a7a        |         |\n| 400004 |      \u8bf7\u6c42\u4f53\u975e json \u683c\u5f0f      |         |\n| 400005 |        \u8bf7\u6c42\u4f53\u7c7b\u578b\u9519\u8bef        |         |\n| 400006 |        \u5fc5\u4f20\u7684\u53c2\u6570\u672a\u4f20        |         |\n| 400007 |         \u4f20\u9012\u975e\u6cd5\u53c2\u6570         |         |\n| 400008 |   \u8bf7\u6c42\u4f53\u7684\u53c2\u6570\u5b57\u6bb5\u7c7b\u578b\u9519\u8bef   |         |\n| 400009 |    \u8bf7\u6c42\u4f53\u7684\u53c2\u6570\u5b57\u6bb5\u503c\u4e3a\u7a7a    |         |\n| 400010 |  \u8bf7\u6c42\u4f53\u7684\u53c2\u6570\u5b57\u6bb5\u503c\u8bbe\u7f6e\u9519\u8bef  |         |\n| 400011 |     base64 \u6570\u636e\u5904\u7406\u5f02\u5e38      |         |\n| 400012 |        \u6587\u4ef6\u683c\u5f0f\u4e0d\u5408\u6cd5        |         |\n| 400013 |      \u6587\u4ef6\u5927\u5c0f\u4e0d\u7b26\u5408\u8981\u6c42      |         |\n| 400014 |      \u8bf7\u6c42\u65f6\u95f4\u8303\u56f4\u4e0d\u5408\u6cd5      |         |\n| 400015 |         \u6587\u4ef6\u4e0b\u8f7d\u9519\u8bef         |         |\n| 400016 |        \u5fc5\u4f20\u7684\u53c2\u6570\u91cd\u590d        |         |\n| 410001 |         \u56fe\u7247\u89e3\u7801\u9519\u8bef         |         |\n| 410002 |      \u56fe\u7247\u5c3a\u5bf8\u4e0d\u7b26\u5408\u8981\u6c42      |         |\n| 420001 |       \u6587\u672c\u957f\u5ea6\u8d85\u8fc7\u9650\u5236       |         |\n| 420002 |       \u6587\u672c\u957f\u5ea6\u4f4e\u4e8e\u9608\u503c       |         |\n| 420003 |         \u4e2d\u6587\u5360\u6bd4\u8fc7\u4f4e         |         |\n| 420004 |      \u6587\u672c\u4e0d\u662f UTF8 \u683c\u5f0f      |         |\n| 430001 |         \u97f3\u9891\u89e3\u7801\u9519\u8bef         |         |\n| 430002 |     \u97f3\u9891\u91c7\u6837\u7387\u4e0d\u7b26\u5408\u8981\u6c42     |         |\n| 430003 |    \u97f3\u9891\u91c7\u6837\u7cbe\u5ea6\u4e0d\u7b26\u5408\u8981\u6c42    |         |\n| 430004 |     \u97f3\u9891\u58f0\u9053\u6570\u4e0d\u7b26\u5408\u8981\u6c42     |         |\n| 430005 |      \u97f3\u9891\u957f\u5ea6\u4e0d\u7b26\u5408\u8981\u6c42      |         |\n| 440001 |         \u89c6\u9891\u89e3\u7801\u9519\u8bef         |         |\n| 450001 |        \u6570\u636e\u5e93\u64cd\u4f5c\u5931\u8d25        |         |\n| 450002 |      \u8bf7\u6c42\u7684\u6570\u636e\u5e93\u4e0d\u5b58\u5728      |         |\n| 450003 |      \u8bf7\u6c42\u7684\u6570\u636e\u5e93\u5df2\u5b58\u5728      |         |\n| 450004 |    \u8bf7\u6c42\u7684\u6570\u636e\u5e93\u5b9e\u4f53\u4e0d\u5b58\u5728    |         |\n| 450005 |    \u8bf7\u6c42\u7684\u6570\u636e\u5e93\u5b9e\u4f53\u5df2\u5b58\u5728    |         |\n| 500001 |  \u670d\u52a1\u63a5\u53e3\u5f02\u5e38\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458  |         |\n| 500002 | \u64cd\u4f5c\u6570\u636e\u5e93\u5f02\u5e38\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458 |         |\n| 500003 |  \u6a21\u578b\u63a8\u7406\u9519\u8bef\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458  |         |\n| 600001 |       \u4eba\u4f53\u7279\u5f81\u63d0\u53d6\u9519\u8bef       |         |\n| 601001 |       \u4eba\u8138\u7279\u5f81\u63d0\u53d6\u9519\u8bef       |         |\n\n",
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "",
            "keywords": "python exception",
            "license": "",
            "maintainer": "",
            "maintainer_email": "",
            "name": "teleexception",
            "package_url": "https://pypi.org/project/teleexception/",
            "platform": null,
            "project_url": "https://pypi.org/project/teleexception/",
            "project_urls": null,
            "release_url": "https://pypi.org/project/teleexception/0.2.9/",
            "requires_dist": null,
            "requires_python": ">=3.6,",
            "summary": "Python Package for tele exception",
            "version": "0.2.9",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 16007800,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "e6958260fbf35f49b31b341557658a42",
                    "sha256": "ea5fdac1b4de5311824b57f6d5ae5b1ebce0ce1088f1160315e124d7f85b8df1"
                },
                "downloads": -1,
                "filename": "teleexception-0.2.9-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "e6958260fbf35f49b31b341557658a42",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.6,",
                "size": 9774,
                "upload_time": "2022-11-01T14:18:29",
                "upload_time_iso_8601": "2022-11-01T14:18:29.716587Z",
                "url": "https://files.pythonhosted.org/packages/07/62/8ab89637f9812abc4e470c04cb8b1da05977c540ae5d6007fa9be9b539a2/teleexception-0.2.9-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    }
}