{
    "0.1.0": {
        "info": {
            "author": "Doru Irimescu",
            "author_email": "",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 4 - Beta",
                "Programming Language :: Python"
            ],
            "description": "exception-with-retry\n====================\n\n\nWraps any method which throws exceptions. Retries calls when exceptions are thrown.\n\n\nDescription\n===========\n\nCheck the [unit tests](https://github.com/doruirimescu/exception-with-retry/blob/master/tests/test_1.py) for usage.\n\n\nMaking Changes & Contributing\n=============================\n\nThis project uses [pre-commit](http://pre-commit.com/), please make sure to install it before making any\nchanges::\n\n    pip install pre-commit\n    cd exception-with-retry\n    pre-commit install\n\nIt is a good idea to update the hooks to the latest version::\n\n    pre-commit autoupdate\n\nDon't forget to tell your contributors to also install and use pre-commit.\n\n\nNote\n====\n\nThis project has been set up using PyScaffold 4.0.2. For details and usage\ninformation on PyScaffold see https://pyscaffold.org/.\n\n\n",
            "description_content_type": "text/markdown; charset=UTF-8",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://github.com/doruirimescu/exception-with-retry/",
            "keywords": "",
            "license": "MIT",
            "maintainer": "",
            "maintainer_email": "",
            "name": "exception-with-retry",
            "package_url": "https://pypi.org/project/exception-with-retry/",
            "platform": "any",
            "project_url": "https://pypi.org/project/exception-with-retry/",
            "project_urls": {
                "Homepage": "https://github.com/doruirimescu/exception-with-retry/"
            },
            "release_url": "https://pypi.org/project/exception-with-retry/0.1.0/",
            "requires_dist": [
                "importlib-metadata ; python_version < \"3.8\"",
                "setuptools ; extra == 'testing'",
                "pytest ; extra == 'testing'",
                "pytest-cov ; extra == 'testing'"
            ],
            "requires_python": "",
            "summary": "Wait and retry calling an exception throwing method.",
            "version": "0.1.0",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 11159086,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "5d4339150ca120288361c48f5c5bb6ea",
                    "sha256": "a01f327fb548910a9e64dfc839db83bd0fc45114bffe175d164d8d43aecbcdb0"
                },
                "downloads": -1,
                "filename": "exception_with_retry-0.1.0-py2.py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "5d4339150ca120288361c48f5c5bb6ea",
                "packagetype": "bdist_wheel",
                "python_version": "py2.py3",
                "requires_python": null,
                "size": 4136,
                "upload_time": "2021-08-12T08:38:35",
                "upload_time_iso_8601": "2021-08-12T08:38:35.333714Z",
                "url": "https://files.pythonhosted.org/packages/e3/4a/c33a572e6dfd0a96793831775b0d37b77a50f06a0e47727e02c8148d3b55/exception_with_retry-0.1.0-py2.py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "83c9d04e9d37f0e94cc1bf3938acc310",
                    "sha256": "919d0dce6198098badaa349e3f02ffa1c76061a49593ff2d4c0bc20ca560b99d"
                },
                "downloads": -1,
                "filename": "exception-with-retry-0.1.0.tar.gz",
                "has_sig": false,
                "md5_digest": "83c9d04e9d37f0e94cc1bf3938acc310",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": null,
                "size": 15041,
                "upload_time": "2021-08-12T08:38:36",
                "upload_time_iso_8601": "2021-08-12T08:38:36.658898Z",
                "url": "https://files.pythonhosted.org/packages/88/d8/702cc8b788bd727f2321fa56aec974f76ceef2bf58029395cd1881520871/exception-with-retry-0.1.0.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    }
}